backup:
  dburl: 120.132.116.155
  dbname: laboratory
  mysqlbin: /usr/local/mysql/bin/
  mail: saya@saya.ac.cn
  savemonth: -1

server:
  port: 8080
#  servlet:
#    context-path: /laboratory

# 固定上传文件的大小
spring:
  servlet:
    multipart:
      maxFileSize: 30MB
      maxRequestSize: 30MB

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false

  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
    static-locations: classpath:/files/


  datasource:
    # Druid连接池配置，官方配置参考：https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.132.116.155/laboratory?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: saya
    password: Saya.ac.cn.666
    driver-class-name: com.mysql.jdbc.Driver
    # Druid其他配置
    druid:
      filter:
        stat:
          slow-sql-millis: 2000
          log-slow-sql: true
      min-idle: 10
      max-active: 20
      filters: stat,wall
      initial-size: 5
      max-wait: 10
      # Druid WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        url-pattern: /*
        enabled: true
      # Druid StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        allow:
        deny:
        url-pattern: /druid/*
        login-password: admin
        reset-enable: true
        login-username: admin
        enabled: true

  mail:
    host: smtp.qq.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    username: 504804540@qq.com
    password: abfekqvcpsbrbhie
    default-encoding: UTF-8

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: ac.cn.saya.laboratory.entity